<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <span class="count-minus">-</span>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                       />
                <span class="count-plus">+</span>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
        <button type="submit"
                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="btn btn-default" 
                style="background:#000;padding: 2.2rem 2.3125rem;;display:inline-flex;">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="34" viewBox="0 0 32 34"><g><g><path fill="#fff" d="M7.186 29.85a3.531 3.531 0 1 1 7.063 0 3.531 3.531 0 0 1-7.063 0z"/></g><g><path fill="#fff" d="M22.096 29.85a3.531 3.531 0 1 1 7.063 0 3.531 3.531 0 0 1-7.063 0z"/></g><g><path fill="#fff" d="M7.931 6.66L6.715 2.972A3.61 3.61 0 0 0 3.34.5H.712a.785.785 0 1 0 0 1.57H3.34a2.04 2.04 0 0 1 1.884 1.373l4.944 15.028-.353.902a3.885 3.885 0 0 0 .314 3.414 3.65 3.65 0 0 0 2.943 1.648h15.302a.785.785 0 1 0 0-1.57H13.072a1.962 1.962 0 0 1-1.61-.941 2.04 2.04 0 0 1-.195-1.884l.47-1.177a1.02 1.02 0 0 0 .04-.588l-.236-.589 15.97-1.648a2.707 2.707 0 0 0 2.394-2.08l1.648-6.945z"/></g></g></svg>
            <span href="#">AGGIUNGI</span>
        </button>
            <!-- <button type="submit"
                    title="<//?= //$block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><///?= //$block->escapeHtml($buttonTitle) ?></span>
            </button> -->
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script>
    require([
        'jquery'
    ],

    function (jQuery) {
        jQuery(document).ready(function() {
                jQuery('.count-minus').click(function () {
                    var $input = jQuery(this).parent().find('input');
                    var count = parseInt($input.val()) - 1;
                    count = count < 1 ? 1 : count;
                    $input.val(count);
                    $input.change();
                    return false;
                });
                jQuery('.count-plus').click(function () {
                    var $input = jQuery(this).parent().find('input');
                    $input.val(parseInt($input.val()) + 1);
                    $input.change();
                    return false;
                });
            });

    });
</script>