<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="34" viewBox="0 0 32 34"><g><g><path fill="#fff" d="M7.186 29.85a3.531 3.531 0 1 1 7.063 0 3.531 3.531 0 0 1-7.063 0z"></path></g><g><path fill="#fff" d="M22.096 29.85a3.531 3.531 0 1 1 7.063 0 3.531 3.531 0 0 1-7.063 0z"></path></g><g><path fill="#fff" d="M7.931 6.66L6.715 2.972A3.61 3.61 0 0 0 3.34.5H.712a.785.785 0 1 0 0 1.57H3.34a2.04 2.04 0 0 1 1.884 1.373l4.944 15.028-.353.902a3.885 3.885 0 0 0 .314 3.414 3.65 3.65 0 0 0 2.943 1.648h15.302a.785.785 0 1 0 0-1.57H13.072a1.962 1.962 0 0 1-1.61-.941 2.04 2.04 0 0 1-.195-1.884l.47-1.177a1.02 1.02 0 0 0 .04-.588l-.236-.589 15.97-1.648a2.707 2.707 0 0 0 2.394-2.08l1.648-6.945z"></path></g></g></svg>
        <span class="text"><?= $block->escapeHtml(__('Carrello')) ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()) :?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else :?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>


