<?php
    $categories = $this->getCategoryCollection();
    $subcategory=$block->getSubCategory();
	$title = $block->getTitle() ? __($block->getTitle()) : 'Naviga';
?>
<?php if ($title):?>
    <?php if(count($subcategory)):?>
<div class="block-title">
	<strong><?php echo $block->escapeHtml($title) ?></strong>
</div>
<?php endif ?>
<?php endif ?>
<?php if(count($subcategory)):?>
    <div class="block-content catalog-subcategory">
        <?php foreach($subcategory as $subcategories):?>
            <span class="subcategory">
                <a href="<?php echo $block->escapeUrl($subcategories->getUrl()) ?>">
                	<span class="subcat-title"><?php echo $block->escapeHtml($subcategories->getName()) ?></span>
        	    </a>
            </span>
        <?php endforeach; ?>
<?php endif ?>
</div>