<?php
/**
 * Bss Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   Bss
 * @package    Bss_ProductsWidgetSlider
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 Bss Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

use Magento\Framework\App\Action\Action;

/**
 * Product list template
 *
 * @var $block \Bss\ProductsWidgetSlider\Block\Product\BestSeller
 * @var $block \Bss\ProductsWidgetSlider\Block\Product\MostView
 * @var $block \Bss\ProductsWidgetSlider\Block\Product\OnSale
 */


?>
<?php // @codingStandardsIgnoreFile ?>
<?php
$enable = $block->getEnableConfig();
if(!$enable) {}
else {
    $_productCollection = $block->createCollection();
    $showSlider = $block->getShowSlider();
    $color = $block->getDotsColor();
    $key = $block->genKey();
    if ($showSlider) {
        $countOnPage = 0;
        $productPerSlide = $block->getProductsPerSlide();
        $showNavigation = $block->getShowSlideNavigation();
        $showArrows = $block->getShowArrows();
        $autoPlayEvery = $block->getAutoPlaySlideEvery();
    }?>
    <?php if (!$_productCollection->count()): ?>

    <?php else: ?>
        <?php
        $title = $block->getWidgetName();
        if(!empty($title)){
            ?>
            <div class="bss-title">
            <h1 class="background"><span><?php echo $block->escapeHtml(__($title)) ?></span></h1>
            </div><?php } ?>
        <!--    -->
        <?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $showPrice = $block->getShowPrice();
        $showWishlist = $block->getShowWishList();
        $showCompare = $block->getShowCompare();
        $showCart = $block->getShowCart();
        $checker = $block->getShowCart();
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="block widget block-viewed-products">
            <div class="block-content">
                <div class="products wrapper <?= $block->escapeQuote($viewMode) ?> products-<?= $block->escapeQuote($viewMode) ?>">
                    <?php $iterator = 1;?>
                    <ol class="products list items product-items bss-slick-slider<?= $block->escapeQuote($key) ?>">
                        <?php /** @var $_product \Magento\Catalog\Model\Product */?>
                        <?php foreach ($_productCollection as $_product): ?>
                            <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info bss-item-theme" data-container="product-grid">
                                <?php
                                if($showSlider){
                                    $countOnPage++;
                                }
                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>
                                <?php // Product Image ?>
                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?= $productImage->toHtml()?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($block->escapeHtml($_product->getName()), null, true);
                                    $info = [];
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                            <?= $block->productAttribute($_product, $block->escapeHtml($_product->getName()), 'name') ?>
                                        </a>
                                    </strong>
                                    <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                    <?php if ($showPrice) { ?>
                                        <div class="bss-price-box">
                                            <?= /* @escapeNotVerified */$block->getProductPrice($_product) ?>
                                        </div>
                                    <?php } ?>
                                    <div class="">
                                        <div class="product actions product-item-actions bss-item-action"<?= $block->escapeQuote(strpos($pos, $viewMode . '-actions') ? $position : '') ?>>
                                            <div class="actions-primary"<?= $block->escapeQuote(strpos($pos, $viewMode . '-primary') ? $position : '' )?>>
                                                <?php if ($_product->getData('stock_status')): ?>
                                                    <?php $postParams = $block->getAddToCartPostParamsAjax($_product); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= /* @NoEscape */$_product->getSku() ?>" action="<?= /* @NoEscape */$postParams['action'] ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= $block->escapeQuote($postParams['data']['product']) ?>">
                                                        <input type="hidden" name="<?= $block->escapeQuote(Action::PARAM_NAME_URL_ENCODED) ?>" value="<?= $block->escapeQuote($postParams['data'][Action::PARAM_NAME_URL_ENCODED]) ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <?php if ($showCart) {

                                                            $postData = $block->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                                            ?>
                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                    class="action tocart primary bss-tocart-theme">
                                                                <?php if($showSlider) {
                                                                    if ($productPerSlide > 5) {
                                                                        if ($productPerSlide >= 8){ ?>
                                                                            <i class="fas fa-shopping-cart"></i>
                                                                            <?php
                                                                        } else { ?>
                                                                            <span><?= $block->escapeHtml(__('Add to')) ?></span>
                                                                            <i class="fas fa-shopping-cart"></i>
                                                                            <?php
                                                                            ?>
                                                                        <?php }} else { ?>
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    <?php } } else{ ?>
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                <?php } ?>
                                                            </button>
                                                        <?php }?>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product->getData('stock_status')): ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable bss-out-stock" title="<?= $block->escapeHtml(__('Out of Stock'))?>">
                                                            <?php if($showSlider) {
                                                                if ($productPerSlide > 5) {
                                                                    if ($productPerSlide >= 8){ ?>
                                                                        <i class="fas fa-ban"></i>
                                                                        <?php
                                                                    } else { ?>
                                                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                        <?php
                                                                        ?>
                                                                    <?php }} else { ?>
                                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                <?php } } else{ ?>
                                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                            <?php } ?>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary bss-action-secondary" data-role="add-to-links">
                                                    <?php if ($block->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */$block->getAddToWishlistParams($_product) ?>'
                                                           class="action towishlist bss-to-wishlist-theme" data-action="add-to-wishlist"
                                                           title="<?= $block->escapeHtml(__('Add to Wish List'))?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <a href="#" class="action tocompare bss-to-compare-theme"
                                                           title="<?= $block->escapeHtml(__('Add to Compare'))?>"
                                                           data-post='<?= /* @noEscape */$block->getPostDataParams($_product) ?>'>
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <?php if ($showDescription): ?>
                                            <div class="product description product-item-description">
                                                <?= $block->escapeHtml($block->productAttribute($_product, $_product->getShortDescription(), 'short_description')) ?>
                                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" title="<?= $block->escapeHtml($_productNameStripped) ?>"
                                                   class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <?= ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
        </div>
        <?= $block->getPagerHtmlBss() ?>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {
                            "product_sku": "<?= /* @NoEscape */$_product->getSku() ?>"
                        }
                    }
                }
            </script>
        <?php endif; ?>
    <?php endif; ?>
    <script type="text/x-magento-init">
    {
        "*":{
            "Bss_ProductsWidgetSlider/js/fontawesome-all":{}
        }
    }
    </script>
    <?php
    if ($showSlider){
        if($countOnPage <= $productPerSlide){
            $showSlider = false;
        }
    }?>
    <?php
    if ($showSlider) { ?>
        <script type="text/x-magento-init">
                {
                    "*": {
                        "Bss_ProductsWidgetSlider/js/slider":{
                            "key": "<?= /* @NoEscape */$key ?>",
                            "productPerSlide": "<?= /* @NoEscape */$productPerSlide ?>",
                            "showNavigation": "<?= /* @NoEscape */$showNavigation ?>",
                            "showArrows": "<?= /* @NoEscape */$showArrows ?>",
                            "autoplayEvery": "<?= /* @NoEscape */$autoPlayEvery ?>"
                        }
                    }
                }
            </script>
        <?php
    }
}
?>
