<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Review\Block\Product\View\ListView $block */

$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)) : ?>
<div class="block review-list" id="customer-reviews">
    <div class="block-content">
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
        <ol class="items review-items">
        <?php foreach ($_items as $_review) : ?>
            <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
            <div class="rev-1">
                <span class="review-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="21" height="20" viewBox="0 0 21 20"><g><g><path fill="#fff" d="M16.822 13.807l-3.018-1.006a.708.708 0 0 0-.225-.037H7.907a.707.707 0 0 0-.225.037l-3.018 1.006a5.62 5.62 0 0 0-3.849 5.34c0 .39.318.708.71.708h18.437a.71.71 0 0 0 .709-.709 5.62 5.62 0 0 0-3.849-5.339z"></path></g><g><path fill="#fff" d="M10.743 0a4.255 4.255 0 0 0-4.255 4.255V7.09a4.259 4.259 0 0 0 4.255 4.255 4.259 4.259 0 0 0 4.255-4.255V4.255A4.255 4.255 0 0 0 10.743 0z"></path></g></g></svg>
                </span>
                <div class="review-details">
                    <p class="review-author">
                        <span class="review-details-label"><?= $block->escapeHtml(__('Review by')) ?></span>
                        <strong class="review-details-value" itemprop="author"><?= $block->escapeHtml($_review->getNickname()) ?></strong>
                    </p>
                </div> 
            </div>
            <div class="rev-2">
                <div class="review-date">
                    <span class="review-details-label"><?= $block->escapeHtml(__('Posted on')) ?></span>
                    <time class="review-details-value" itemprop="datePublished" datetime="<?= $block->escapeHtmlAttr($block->formatDate($_review->getCreatedAt(), $format)) ?>"><?= $block->escapeHtml($block->formatDate($_review->getCreatedAt(), $format)) ?></time>
                </div>
                <?php if (count($_review->getRatingVotes())) : ?>
                    <div class="review-ratings">
                    <?php foreach ($_review->getRatingVotes() as $_vote) : ?>
                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                        <span class="label rating-label"><span><?= $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                        <div class="rating-result" title="<?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
                            <meta itemprop="worstRating" content = "1"/>
                            <meta itemprop="bestRating" content = "100"/>
                            <span style="width:<?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
                                <span itemprop="ratingValue"><?= $block->escapeHtml($_vote->getPercent()) ?>%</span>
                            </span>
                        </div>
                    </div>
                    <?php endforeach; ?>
                    </div>
                <?php endif; ?> 
            </div>
            <div class="rev-3">
                <div><strong>
                    <?= /* @noEscape */ nl2br($block->escapeHtml($_review->getTitle())) ?>\
                </strong></div>
                <div class="review-content" itemprop="description">
                    <?= /* @noEscape */ nl2br($block->escapeHtml($_review->getDetail())) ?>
                </div>  
            </div>
            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php endif ;?>
<?php  if(empty($_items)) :?>
<div class="review-empty">This product has not received a written review yet.
    Let others know what do you think and be the first to write a review.
</div>
<?php endif ;?>