<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */

$_rating=$block->getAllStar($block->getProductId());
$_rating_reverse=array_reverse($_rating);
//Total Reviews
$_total_reviews=$block->getCollectionSize();

//Calculating Average Rating
$_avg=0;
$_ratingstar=5;
foreach ($_rating as $_count):
    if($_ratingstar>0){
        $_avg=$_avg+($_count['value']*$_ratingstar);
        $_ratingstar=$_ratingstar-1;
    }
endforeach;
if($_total_reviews>0){
    $_avg=number_format(($_avg)/($_total_reviews),1);
}
?>
<div id="product-reviews-container">
    <div class="block-title">
        <strong>Recensioni dei clienti</strong>
    </div>
    <div class="block-container">
        <div id="average-rating">
            <div class="rating-content">
                <div class="rating-label"><?php echo $_avg?> su 5</div>
                <div class="rating-result">
                    <span class="rating-span" style="width:<?php echo (($_avg*100)/5) ?>%"></span>
                </div>
            </div>
            <div class="rating-total"><?php echo $_total_reviews ?> recensioni clienti</div>
            <div class="rating-percent-container">
                <?php   $i=1;
                        foreach ($_rating_reverse as $_count):
                            if($_total_reviews>0){
                                $_rating_percent=round(($_count['value']*100)/$_total_reviews,1);
                            }
                            else{
                                $_rating_percent=0;
                            }
                ?>
                <div class="rating-percent">
                    <span><?php echo $i ?> stella</span>
                    <progress id="progressBar" value="<?php echo $_rating_percent ?>" max="100"></progress>
                    <span><?php echo $_rating_percent ?>%</span>
                </div>
                <?php $i++; 
                    endforeach; ?>
            </div>


            <div class="product-review-form-container">
                <div class="review-form-title">Recensisci Questo Prodotto</div>
                <div class="review-form-subtitle">Condividi i tuoi pensieri con altri clienti</div>
                <button type="button" class="btn btn-review">SCRIVI UNA RECENSIONE</button> 
            </div>  
        </div>
        <div id="product-review-container" data-role="product-review"></div>
        <?= $block->getChildHtml() ?>
        </div>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
<script>
    require([
        'jquery'
    ],

    function (jQuery) {
        jQuery(document).ready(function() {
                jQuery('.product-review-form-container .btn-review').click(function () {
                    jQuery('.block.review-add').fadeIn();
                });
            });

    });
</script>
