<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$title = $objectManager->get('Magento\Framework\View\Page\Title');
?>
<div class="mobile-toolbar" id="mobile-toolbar">
    <div class="mobile-page-title"> <?php echo $title->getShort(); ?></div>
    <button type="submit" style="background:none;border:none;" onclick="window.history.go(-1); return false;" >
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24pt" height="24pt" viewBox="0 0 24 24" version="1.1">
        <g id="surface1">
            <path style=" stroke:none;fill-rule:nonzero;fill:rgb(12.941176%,58.823529%,95.294118%);fill-opacity:1;" d="M 23.5 11.492188 L 1.707031 11.492188 L 9.855469 3.347656 C 10.046875 3.148438 10.039062 2.832031 9.84375 2.640625 C 9.648438 2.453125 9.339844 2.453125 9.148438 2.640625 L 0.148438 11.640625 C -0.046875 11.835938 -0.046875 12.152344 0.148438 12.347656 L 9.148438 21.347656 C 9.339844 21.546875 9.65625 21.550781 9.855469 21.359375 C 10.054688 21.167969 10.058594 20.851562 9.867188 20.652344 C 9.863281 20.648438 9.859375 20.644531 9.855469 20.640625 L 1.707031 12.492188 L 23.5 12.492188 C 23.777344 12.492188 24 12.269531 24 11.992188 C 24 11.714844 23.777344 11.492188 23.5 11.492188 Z M 23.5 11.492188 "/>
            <path style=" stroke:none;fill-rule:nonzero;fill:rgb(43.921569%,43.921569%,43.921569%);fill-opacity:1;" d="M 9.5 21.492188 C 9.367188 21.492188 9.238281 21.441406 9.144531 21.347656 L 0.144531 12.347656 C -0.046875 12.152344 -0.046875 11.835938 0.144531 11.640625 L 9.144531 2.640625 C 9.34375 2.449219 9.660156 2.453125 9.851562 2.652344 C 10.039062 2.847656 10.039062 3.152344 9.851562 3.347656 L 1.207031 11.992188 L 9.851562 20.640625 C 10.046875 20.832031 10.050781 21.148438 9.855469 21.347656 C 9.761719 21.441406 9.632812 21.492188 9.5 21.492188 Z M 9.5 21.492188 "/>
            <path style=" stroke:none;fill-rule:nonzero;fill:rgb(43.921569%,43.921569%,43.921569%);fill-opacity:1;" d="M 23.5 12.492188 L 0.5 12.492188 C 0.222656 12.492188 0 12.269531 0 11.992188 C 0 11.714844 0.222656 11.492188 0.5 11.492188 L 23.5 11.492188 C 23.777344 11.492188 24 11.714844 24 11.992188 C 24 12.269531 23.777344 12.492188 23.5 12.492188 Z M 23.5 12.492188 "/>
        </g>
    </svg>
    </button>
</div>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <div>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <!-- <?//= $block->getReviewsSummaryHtml($_product, $templateType) ?> -->
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?php if ($_product->isAvailable()) :?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>
                        </div>

                        <div class="float-cart" style="position:absolute">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($_product->isSaleable()) :?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="btn btn-default" style="background:#000;padding:1.5rem 2.3125rem;display:inline-flex;">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="34" 
                                                    viewBox="0 0 32 34">
                                                    <g><g>
                                                        <path fill="#fff" d="M7.186 29.85a3.531 3.531 0 1 1 7.063 0 3.531 3.531 0 0 1-7.063 0z"/></g>
                                                        <g><path fill="#fff" d="M22.096 29.85a3.531 3.531 0 1 1 7.063 0 3.531 3.531 0 0 1-7.063 0z"/></g>
                                                        <g><path fill="#fff" d="M7.931 6.66L6.715 2.972A3.61 3.61 0 0 0 3.34.5H.712a.785.785 0 1 0 0 1.57H3.34a2.04 2.04 0 0 1 1.884 1.373l4.944 15.028-.353.902a3.885 3.885 0 0 0 .314 3.414 3.65 3.65 0 0 0 2.943 1.648h15.302a.785.785 0 1 0 0-1.57H13.072a1.962 1.962 0 0 1-1.61-.941 2.04 2.04 0 0 1-.195-1.884l.47-1.177a1.02 1.02 0 0 0 .04-.588l-.236-.589 15.97-1.648a2.707 2.707 0 0 0 2.394-2.08l1.648-6.945z"/>
                                                    </g></g>
                                                </svg>
                                                <span href="#">
                                                    AGGIUNGI
                                                </span>
                                            </button>
                                        </form>
                                    <?php else :?>
                                        <?php if ($_product->isAvailable()) :?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else :?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                
                                </div>
                            </div>
                        </div>
                        <div class="product-item-actions">
                            <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($_product->isSaleable()) :?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"  
                                                style="background:none;border:none;">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="34" viewBox="0 0 32 34">
                                                    <g>
                                                        <g><path fill="#4c4d4f" d="M7.186 29.85a3.531 3.531 0 1 1 7.063 0 3.531 3.531 0 0 1-7.063 0z"/></g>
                                                        <g><path fill="#4c4d4f" d="M22.096 29.85a3.531 3.531 0 1 1 7.063 0 3.531 3.531 0 0 1-7.063 0z"/></g>
                                                        <g><path fill="#4c4d4f" d="M7.931 6.66L6.715 2.972A3.61 3.61 0 0 0 3.34.5H.712a.785.785 0 1 0 0 1.57H3.34a2.04 2.04 0 0 1 1.884 1.373l4.944 15.028-.353.902a3.885 3.885 0 0 0 .314 3.414 3.65 3.65 0 0 0 2.943 1.648h15.302a.785.785 0 1 0 0-1.57H13.072a1.962 1.962 0 0 1-1.61-.941 2.04 2.04 0 0 1-.195-1.884l.47-1.177a1.02 1.02 0 0 0 .04-.588l-.236-.589 15.97-1.648a2.707 2.707 0 0 0 2.394-2.08l1.648-6.945z"/></g>
                                                    </g>
                                                </svg>
                                            </button>
                                        </form>
                                    <?php else :?>
                                        <?php if ($_product->isAvailable()) :?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else :?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                
                            </div>
                        </div>            
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            
                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="bottom-toolbar">
    <?= $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
